### PR TITLE
ENH: No longer force all non-optional params to have EnsureNone()

### PR DESCRIPTION
**Pull request by mih**
Our API functions have a problem. Most of them need a dataset to work,
but we have logic to figure the particular dataset out automatically,
hence usually: dataset=None. As this must be the first argument, we
cannot have positional args, which is not nice.

This commit mitigates the cosmetics of the problem and removes the need
to have EnsureNone() for all kwargs that are nevertheless required to
have a value other than none.

Not ideal, but can't think of something better.

### CODE REVIEW

**Comment by yarikoptic** [comment]
I am probably missing the point... but wouldn't the problem go away if `dataset` kwarg just gets positioned last among all the args?  then positional args would be all fine and when necessary dataset could be provided as kwarg

**Comment by yarikoptic** [comment]
in python3 it is even possible to enforce that dataset would always need to be provided as kwarg (not positional arg): http://stackoverflow.com/a/14298976/1265472

**Comment by mih** [comment]
`dataset` needs to go first, because we bind those functions to the Dataset class (i.e. they take the role of `self`).

**Comment by yarikoptic** [comment]
oh... rright, forgot about that.  But since all of this is short of magic:
http://nbviewer.jupyter.org/url/www.onerussian.com/tmp/bind_methods1.ipynb
and compatible with both python 2 and 3

there is a runtime penalty of cause but since those are interface functions, I don't think it would be anything to worry about

**Comment by mih** [comment]
Excellent point! Thanks.

On Mon, Apr 4, 2016 at 5:35 PM, Yaroslav Halchenko <notifications@github.com

> wrote:
> 
> oh... rright, forgot about that. But since all of this is short of magic:
> http://nbviewer.jupyter.org/url/www.onerussian.com/tmp/bind_methods1.ipynb
> and compatible with both python 2 and 3
> 
> there is a runtime penalty of cause but since those are interface
> functions, I don't think it would be anything to worry about
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bpoldrack/datalad/pull/25#issuecomment-205353886

## 

Michael Hanke
http://mih.voxindeserto.de

**Comment by bpoldrack** [comment]
Did it here:
https://github.com/datalad/datalad/pull/388/commits/e2c1de41003e4c94a6683069fb53329d0582db21

**Pull request closed without merging**
